project_id                  = "your-gcp-project-id"
region                      = "us-central1"
service_account_id          = "my-service-account"
service_account_display_name = "My Service Account"
bucket_name                 = "my-unique-bucket-name"
